### ISSUE TITLE
too many arguments in call to ytypes.Unmarsha

### ISSUE THREAD

**Issue by adibrastegarnia** [openconfig/ygot#287]
I opened an issue in gnxi tool github but somehow related to ygot as well: 

https://github.com/google/gnxi/issues/70

ygot is used in the gnmi target in gnxi github tools and when I build it using dep or go modules, I am getting the following error: 

```
pkg/gnmi/modeldata/gostruct/generated.go:71:63: undefined: ytypes.UnmarshalOpt
pkg/gnmi/modeldata/gostruct/generated.go:81:25: too many arguments in call to ytypes.Unmarshal
```

**Comment by adibrastegarnia** [comment]
To solve this problem, a new release is needed.

**Comment by robshakir** [comment]
Thanks -- I've tagged a new release here, but pulling the latest `HEAD@master` should fix this too.

**Comment by adibrastegarnia** [comment]
Thanks. Yes I fixed the issue that way but that is good to have a new release to get it automatically.

**Comment by adibrastegarnia** [comment]
@robshakir 

It looks like the tag is still not visible to "go get" and it cannot find it. Do you think it takes sometime to be visible? 

P.S. We already fixed the problem by getting the master branch but I am curious to know why the tag is not visible yet to go get.

**Comment by adibrastegarnia** [comment]
@robshakir 

Please fix the tag from 0.6.0 to v0.6.0. I think that is the problem.
